### ISSUE TITLE
Project Proposal

### ISSUE THREAD

**Issue by jenkennedy** [jbotoro/Beaucoup#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [ ] Correctly formatted
    - [ ] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments

---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [ ] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [ ] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [ ] Each MVP is broken down into bullet points

## Comments

---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [ ] unique
    - [ ] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [ ] Correctly formatted
    - [x] schema is written in a table format
    - [ ] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [ ] columns names are lowercased and snaked_cased and `back_ticked`

## Comments

---

# Sample State

- [x] State shape is flat!
- [ ] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [ ] Correctly formatted
    - [ ] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments

---

# Backend Routes

- [ ] Contains the following sections: HTML, API Endpoints(Backend)
- [ ] Each route has a description
- [ ] API Endpoint routes contains wildcard variables written in `snake_case`
- [ ] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [ ] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments

---

# Frontend Routes

- [ ] Frontend routes contains wildcard variables written in `camelCase`
- [ ] Correctly formatted
    - [ ] Routes are displayed with `inline coding text` (backticks)

## Comments

**Comment by mwmadsen67** [comment]
Home Page:
- Needs links to all the design docs

MVP List:
- Needs to be formatted. Please check the [bluebird](https://github.com/appacademy/bluebird/wiki) example.
- Should have multiple bullet points explaining each MVP.
- Please include expected dates to finish and time estimates.

Sample State:
- Sample state is flat!
- The formatting is off, should be in 
```javascript
{
}
```

**Comment by mwmadsen67** [comment]
MVP List:
- It looks like your bullet points are all back ticked, I think it would be easier to read if they were not backticked.
- I would put the myStuff MVP before search since it's the CRUD feature.

Backend Routes:
- Should be formatted like the bluebird example.
- Each route should have a description.
- Wildcards should be in snake_case. 
Remember, these routes are referring to your Rails backend. The routes in here will be how you interact with the data you have in your database (schema).

Frontend Routes:
- Should be formatted like the bluebird example.
- If the backend routes are a way of planning out your Rails backend, your frontend routes are a way of planning out which React components you will have to build.
- Try to plan out not just the videos home page, but seasons, shows, episodes, myStuff etc.

Feel free to comment on here or message me on slack any specific questions you have on planning this out.

**Comment by mwmadsen67** [comment]
Notes from meeting:
- Make season a integer column in shows instead of its own table
- optional show_id or movie_id in myStuff, we can talk more about implementation later
- mvp: prod readme at end, videos is one mvp, add categories mvp after mystuff
